### ISSUE TITLE
help

### ISSUE THREAD

**Issue by creyes12345** [SalehMogren/E-diet#24]
hi, im kinda newbie. i'l have this issue in healthsetup. thank you in advance.
 [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'uid' was called on null.

**Comment by SZ4M** [comment]
@creyes12345 welcome,
could you provide a screen shot for the screen and print of the logs.

**Comment by creyes12345** [comment]
thank you for your response.
`W/GooglePlayServicesUtil( 1786): Google Play Store is missing.
E/flutter ( 1786): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [firebase_auth/api-not-available] The requested API is not available.
E/flutter ( 1786): #0      catchPlatformException (package:firebase_auth_platform_interface/src/method_channel/utils/exception.dart:20:3)
E/flutter ( 1786): #1      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter ( 1786): #2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 1786): #3      _FutureListener.handleError (dart:async/future_impl.dart:169:20)
E/flutter ( 1786): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:716:47)
E/flutter ( 1786): #5      Future._propagateToListeners (dart:async/future_impl.dart:737:24)
E/flutter ( 1786): #6      Future._completeError (dart:async/future_impl.dart:547:5)
E/flutter ( 1786): #7      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
E/flutter ( 1786): #8      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 1786): <asynchronous suspension>
E/flutter ( 1786):
E/flutter ( 1786): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'uid' was called on null.
E/flutter ( 1786): Receiver: null
E/flutter ( 1786): Tried calling: uid
E/flutter ( 1786): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 1786): #1      _HealthSetUpState.build.<anonymous closure> (package:e_diet/Pages/AccountSetUp/HealthSetUp.dart:162:38)
E/flutter ( 1786): #2      _HealthSetUpState.build.<anonymous closure> (package:e_diet/Pages/AccountSetUp/HealthSetUp.dart:158:30)
E/flutter ( 1786): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:991:20)
E/flutter ( 1786): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 1786): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter ( 1786): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 1786): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter ( 1786): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 1786): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter ( 1786): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter ( 1786): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter ( 1786): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter ( 1786): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter ( 1786): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:381:19)
E/flutter ( 1786): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:361:22)
E/flutter ( 1786): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter ( 1786): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:316:7)
E/flutter ( 1786): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:280:5)
E/flutter ( 1786): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:238:7)
E/flutter ( 1786): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:221:7)
E/flutter ( 1786): #21     _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter ( 1786): #22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 1786): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter ( 1786): #24     _invoke1 (dart:ui/hooks.dart:180:10)
E/flutter ( 1786): #25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:276:7)
E/flutter ( 1786): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
E/flutter ( 1786):
D/InputConnectionAdaptor( 1786): The input method toggled cursor monitoring on``

![Capture](https://user-images.githubusercontent.com/85437664/120924188-00f8c780-c705-11eb-9cd8-4859f7c106fd.PNG)

**Comment by SZ4M** [comment]
are you using your own firebase project?

**Comment by creyes12345** [comment]
can i email you ?

**Comment by SZ4M** [comment]
feel free to contact me on Discord @SZ4M#8565
